export const TONE_CLASSES: Record<string, string> = {
  pending: 'bg-status-pending-bg text-status-pending',
  confirmed: 'bg-status-confirmed-bg text-status-confirmed',
  approved: 'bg-status-confirmed-bg text-status-confirmed',
  cancelled: 'bg-status-cancelled-bg text-status-cancelled',
  rejected: 'bg-status-cancelled-bg text-status-cancelled',
  completed: 'bg-status-completed-bg text-status-completed',
  active: 'bg-status-confirmed-bg text-status-confirmed',
  inactive: 'bg-status-cancelled-bg text-status-cancelled',
  bot: 'bg-status-confirmed-bg text-status-confirmed',
  human: 'bg-status-completed-bg text-status-completed',
  stuck: 'bg-status-cancelled-bg text-status-cancelled',
  parse_error: 'bg-status-cancelled-bg text-status-cancelled',
  guardian_link_request: 'bg-status-pending-bg text-status-pending',
  reactivation_request: 'bg-status-pending-bg text-status-pending',
  booking_request: 'bg-status-pending-bg text-status-pending',
  question: 'bg-status-pending-bg text-status-pending',
  will_send: 'bg-status-confirmed-bg text-status-confirmed',
  will_skip: 'bg-status-pending-bg text-status-pending',
  sent: 'bg-status-confirmed-bg text-status-confirmed',
  delivered: 'bg-status-confirmed-bg text-status-confirmed',
  read: 'bg-status-confirmed-bg text-status-confirmed',
  failed: 'bg-status-cancelled-bg text-status-cancelled',
  undeliverable: 'bg-status-cancelled-bg text-status-cancelled',
  skipped: 'bg-status-pending-bg text-status-pending',
  no_login: 'bg-status-pending-bg text-status-pending',
  invited: 'bg-status-completed-bg text-status-completed',
}
